<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Assets</key>
  <array>
    <dict>
      <key>Languages</key>
      <array>
	<string>en-US</string>
      </array>
      <key>Compatibility</key>
      <integer>12</integer>
      <key>Version</key>
      <integer>199</integer>
    </dict>
  </array>
  <key>Source</key>
  <string>Preinstalled</string>
  <key>FormatVersion</key>
  <integer>1</integer>
  <key>LastUpdated</key>
  <date>2021-01-15T01:02:23Z</date>
</dict>
</plist>
